version: 2
updates:
  # Go modules dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
